version: "3.8"

services:
  mysql:
    container_name: starter-mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    container_name: starter-backend
    image: starter-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
  
  frontend:
    container_name: starter-frontend
    image: starter-frontend
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
